# -- Contents automatically generated by generate_classes.py on 2021-01-02T17:38:04.806261
from typing import Optional

import attr

from .enums import ExtrapolationTypes, InterpolationAlgorithms
from .meta import enum_fields


@attr.s(
    auto_attribs=True,
    repr=False,
    frozen=True,
    kw_only=True,
    field_transformer=enum_fields,
)
class Deletable:
    """
    The base schema for a property whose value may be deleted.
    """

    delete: Optional[bool] = None


@attr.s(
    auto_attribs=True,
    repr=False,
    frozen=True,
    kw_only=True,
    field_transformer=enum_fields,
)
class Interpolatable:
    """
    The base schema for a property whose value may be determined by interpolating
    over provided time-tagged samples.
    """

    epoch: Optional[str] = None
    interpolationAlgorithm: Optional[InterpolationAlgorithms] = None
    interpolationDegree: Optional[int] = None
    forwardExtrapolationType: Optional[ExtrapolationTypes] = None
    forwardExtrapolationDuration: Optional[int] = None
    backwardExtrapolationType: Optional[ExtrapolationTypes] = None
    backwardExtrapolationDuration: Optional[int] = None
